#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


ROLE_TRAITS = {
    "architect": {"sandbox_mode": "read-only", "execution": "sub"},
    "backend-engineer": {"execution": "main"},
    "backend-reviewer": {"sandbox_mode": "read-only", "execution": "sub"},
    "database-reviewer": {"sandbox_mode": "read-only", "execution": "sub"},
    "design-reviewer": {"sandbox_mode": "read-only", "execution": "sub"},
    "devops": {"execution": "main"},
    "devops-reviewer": {"sandbox_mode": "read-only", "execution": "sub"},
    "frontend-engineer": {"execution": "main"},
    "frontend-reviewer": {"sandbox_mode": "read-only", "execution": "sub"},
    "git-orchestrator": {"execution": "main"},
    "product-manager": {"sandbox_mode": "read-only", "execution": "sub"},
    "project-manager": {"sandbox_mode": "read-only", "execution": "sub"},
    "qa-engineer": {"execution": "main"},
    "qa-reviewer": {"sandbox_mode": "read-only", "execution": "sub"},
    "technical-writer": {"execution": "sub"},
    "ui-ux-designer": {"execution": "main"},
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate per-role Codex agent TOML configs with shared defaults."
    )
    parser.add_argument(
        "--output-dir",
        default=str(Path(__file__).resolve().parents[1] / "agents" / "config"),
        help="Directory where generated role TOMLs are written.",
    )
    parser.add_argument(
        "--default-model",
        default="gpt-5.4",
        help="Default model written into each generated role config.",
    )
    parser.add_argument(
        "--default-reasoning",
        default="medium",
        help="Default reasoning_effort written into each generated role config.",
    )
    return parser.parse_args()


def render_role_config(role_name: str, default_model: str, default_reasoning: str) -> str:
    traits = ROLE_TRAITS[role_name]
    lines = [
        "# Generated by .codex/scripts/render-agent-configs.py. Do not edit.",
        f'model = "{default_model}"',
        f'reasoning_effort = "{default_reasoning}"',
    ]
    if "sandbox_mode" in traits:
        lines.append(f'sandbox_mode = "{traits["sandbox_mode"]}"')
    lines.append(f'execution = "{traits["execution"]}"')
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    output_dir = Path(args.output_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    for role_name in sorted(ROLE_TRAITS):
        target = output_dir / f"{role_name}.toml"
        target.write_text(
            render_role_config(role_name, args.default_model, args.default_reasoning),
            encoding="utf-8",
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
